# Generated by Django 4.2 on 2023-04-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0002_userprofile_remove_profile_dob_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2),
        ),
    ]
