# Generated by Django 4.2 on 2023-04-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0003_remove_profile_gender_userprofile_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='PatientProfile',
        ),
    ]
